Add improved documentation for the README, INSTALLATION and CONTRIBUTION
Arelle/Arelle pull request #154
Opened 2022-02-23 21:24 UTC by derekgengenbacher-wf

#### Description:
The documentation in Arelle needed to be refreshed and updated. As part of this update we are adding clearer instructions on how to contribute to the Arelle project.

#### Testing:
This is a documentation change only and thus does not require testing.

**review**:
@hermfischer-wf
cc: @austinmatherne-wk @derekgengenbacher-wf @sagesmith-wf

2022-02-23 22:05 UTC, austinmatherne-wk approved these changes

2022-02-23 22:05 UTC, austinmatherne-wk commented on CONTRIBUTING.md
> +  <div align="center">
nit: unexpected indention

2022-02-23 23:28 UTC, hermfischer-wf approved these changes

2022-02-28 20:25 UTC, austinmatherne-wk approved these changes

2022-02-28 21:27 UTC, merged

2022-02-28 22:03 UTC, hermfischer-wf requested changes
### section: Contributor License Agreements

Regarding: "If you work for a company that wants to allow you to contribute your work..."

Wording on the website: "If you are an individual, not under employee or works for hire agreement (e.g. student), please use the [Individual Contributor](https://arelle.org/arelle/wp-content/uploads/2010/11/ContributorLicenseForIndividuals.txt) agreement, otherwise the [Corporate Contributor ](https://arelle.org/arelle/wp-content/uploads/2010/11/ContributorLicenseForEmployees.txt)agreement. The reason why you need to use the corporate agreement if employed is because employment agreements and employment laws give intellectual property rights to the employer, so it is necessary for the employer to be part of that agreement."

The important issue is that the individual contributor agreement can't be used by somebody under a usual works-for-hire (employee) agreement because those give the employer ownership of all IP, and we don't know the precise wording of each individual's agreement (they usually are non-disclosable)  

Suggest some change is needed here for this point.

### section: General guidelines and philosophy for contribution

before make, I suggest "please", seems petty but...

"When you contribute a new feature or plugin to Arelle" is used in 3 bullets. Suggest putting the three subordinate phrases as sub-bullets under this phrase?

### section: License

I think the CLA licenses Workiva to be the licensor of pulled code.  There shouldn't be newer or overriding license terms from contributions to be cast upon the whole project, scary.

However *plugins* may be independently authored and maintained (EFM, EdgarRenderer, Xule) and we should request that the __pluginInfo__ contain properly displayable license author and copyright.  If a contributor withholds transferring ownership to Workiva (SEC, Xbrl.us) this needs to be discoverable.  If a plugin depends on features copyright by others those copyrights may need to be in __pluginInfo__.

*No viral license*:  No GNU-like licenses can be accepted under the CLA but the contribution may incorporate GNU-like licensed library modules (see plugin internet/proxyNTLM/__init__.py).  In this case the GNU-licensed code cannot be included in core-Arelle, so that an "end user action" is required to cause it's activation.

### section: Installation

I think Windows has to be 10 or 11, macOS (lower case m, no space between mac and OS) needs to be 11 or 12, and only unixes and linuxes compatible with recent Ubuntu or RedHat are supported.

### section: Features

Drop Global Filer Manual? (I don't think anybody uses it nor do I know if it still works). 

table linkbase (Eurofiling version) - we dropped the pre-REC Eurofiling version support

Quickbooks integration hasn't been tested in a long time but it still sounds like good eye-candy.