Convert formula tests to pytest
Arelle/Arelle pull request #185
Opened 2022-05-02 05:45 UTC by stevenbronson-wk

The '30000 Assertions/31140-ConsistencyAssertion-StaticAnalysis-missingFormulae/V-01' test case fails right now in Arelle.

I updated validation_util to support single test cases so that you don't have to run the entire suite to debug a single case.

#### Steps to Test
```$ pytest tests/integration_tests/validation/formula```
Expect 680 passed and 1 xfailed.

```$ python -m scripts.conformance_suites.run_formula_conformance_suite; fgrep -c ,pass, Formula-test-report.csv```
Expect 680.

**review**:
@Arelle/arelle

2022-05-02 15:34 UTC, derekgengenbacher-wf commented on tests/integration_tests/validation/formula/test_formula_conformance_suite.py
> +        pytest.xfail(f"missing formula test '{bad_id}' doesn't work yet")
Nice

2022-05-02 15:34 UTC, derekgengenbacher-wf approved these changes

2022-05-02 15:44 UTC, austinmatherne-wk submitted a review, later dismissed

2022-05-02 17:32 UTC, sagesmith-wf submitted a review, later dismissed

2022-05-02 18:56 UTC, hermfischer-wf requested changes
The formula tests are in several parts, of which #1 is implemented:

# Formula main suite (entry index.xml in formula suite)
 *  may need `--plugin formulaXPathChecker --check-formula-restricted-XPath`

# Formula Registry suite (entry function-registry/registry-index.xml)
 * may need `--plugin formulaXPathChecker --check-formula-restricted-XPath`

# Specific subsuites under tests/60000 Extension (which may not be covered by top level index.xml
 * 60100 GenericMessages-Processing
 * 60110 AssertionSeverity-Processing
 * 60111 AssertionSeverity-2.0-Processing
 * 60200 CustomXPathFuctions-Processing
 * 61000 AspectCoverFilter-Processing
 * 61100 ConceptRelationsFilter-Processing
 * 70000 Generic Linkbase tests indexed by index-gnl.xml

2022-07-28 18:59 UTC, aviary2-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2022-07-29 00:24 UTC, austinmatherne-wk approved these changes

2022-08-01 15:00 UTC, sagesmith-wf submitted a review, later dismissed

2022-09-28 17:26 UTC, sagesmith-wf approved these changes

2022-09-28 17:35 UTC, aaroncameron-wk approved these changes

2022-09-28 19:04 UTC, austinmatherne-wk approved these changes

2022-09-28 20:42 UTC, derekgengenbacher-wf approved these changes

2022-09-28 20:43 UTC, derekgengenbacher-wf commented
QA +10 CI succeeded.

2022-09-28 20:43 UTC, merged